
replicaCount: 2
iamRole: k8s-jenkins

container:
  #repository: myrepo/kekseapp        #TODO: provide via commandline param
  #tag: 1.0                           #TODO: provide via commandline param
  pullPolicy: IfNotPresent
  livenessEndpoint: /actuator/health
  readynessEndpoint: /actuator/health
  limits:
    cpu: 2000m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

service:
  type: ClusterIP
  trafficPort: 8080
  healthPort: 8080

ingress:
  #dnsDomain: example.com             #TODO: provide via commandline param
  path: /
  dnsName: kekseapp
  forceSsl: true
  validCidrs: 0.0.0.0/0
